cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(module10_http_proxy LANGUAGES CXX)
  set(CMAKE_CXX_STANDARD 17)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  enable_testing()
endif()

add_executable(module10_http_proxy main.cpp)
if(NOT CMAKE_CXX_STANDARD)
  set_property(TARGET module10_http_proxy PROPERTY CXX_STANDARD 17)
  set_property(TARGET module10_http_proxy PROPERTY CXX_STANDARD_REQUIRED ON)
endif()
if(MSVC)
  target_compile_options(module10_http_proxy PRIVATE /utf-8)
endif()
add_test(NAME module10_http_proxy COMMAND module10_http_proxy)
