cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(module09_epoll_coro LANGUAGES CXX)
  set(CMAKE_CXX_STANDARD 20)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  enable_testing()
endif()

add_executable(module09_epoll_coro main.cpp)
set_property(TARGET module09_epoll_coro PROPERTY CXX_STANDARD 20)
set_property(TARGET module09_epoll_coro PROPERTY CXX_STANDARD_REQUIRED ON)
find_package(Threads REQUIRED)
target_link_libraries(module09_epoll_coro PRIVATE Threads::Threads)
if(MSVC)
  target_compile_options(module09_epoll_coro PRIVATE /utf-8)
endif()
add_test(NAME module09_epoll_coro COMMAND module09_epoll_coro)
