cmake_minimum_required(VERSION 3.20)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(module13_interview LANGUAGES CXX)
  set(CMAKE_CXX_STANDARD 17)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  enable_testing()
endif()

add_executable(module13_interview main.cpp)
if(NOT CMAKE_CXX_STANDARD)
  set_property(TARGET module13_interview PROPERTY CXX_STANDARD 17)
  set_property(TARGET module13_interview PROPERTY CXX_STANDARD_REQUIRED ON)
endif()
find_package(Threads REQUIRED)
target_link_libraries(module13_interview PRIVATE Threads::Threads)
if(MSVC)
  target_compile_options(module13_interview PRIVATE /utf-8)
endif()
add_test(NAME module13_interview COMMAND module13_interview)
